modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "LGPL-3.0-only"
issueTrackerURL = "https://github.com/krampus/LegendaryBlockEntities/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}

Forge port by Krampus. Original mod: Enhanced Block Entities by FoundationGames (https://github.com/FoundationGames/EnhancedBlockEntities), licensed LGPL-3.0.'''
displayURL = "https://github.com/krampus/LegendaryBlockEntities"

[[dependencies.legendaryblockentities]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.legendaryblockentities]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.legendaryblockentities]]
modId="quark"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.legendaryblockentities]]
modId="betterend"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.legendaryblockentities]]
modId="bclib"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.legendaryblockentities]]
modId="betternether"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.legendaryblockentities]]
modId="ironchest"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"
